import { Link } from 'react-router-dom'
import { ConceptImage } from '../../components/ConceptImage'
import { ExampleChecklist } from '../../components/ExampleChecklist'
import { processSteps, proposalPieces } from '../../content/es/refactor'

export function HomePage() {
  return <main id="contenido" className="narrative-home">
    <section className="narrative-hero page-shell" aria-labelledby="hero-title"><div className="narrative-hero__copy"><p className="eyebrow">Sinoikía · Habitar juntos</p><h1 id="hero-title">El futuro es rural.</h1><p className="narrative-hero__lead">Pero para vivir en un pueblo no basta con encontrar una casa.</p><p>Vivienda, trabajo, servicios, movilidad y comunidad tienen que encajar. Sinoikía ayuda a los pueblos a descubrir qué oportunidades pueden construir con lo que ya tienen, qué les falta y qué necesitan resolver antes de buscar a las personas que puedan hacerlas realidad.</p><div className="narrative-actions"><Link className="button button--primary" to="/descubrir">Quiero descubrir dónde encajo</Link><Link className="button button--ghost" to="/municipios">Quiero activar mi municipio</Link></div><p className="hero-support">Sinoikía significa «habitar juntos».</p></div><ConceptImage id="hero" priority caption="Escena conceptual: un territorio habitado y conectado." /></section>

    <section id="problema" className="narrative-section narrative-section--soft" aria-labelledby="problem-title"><div className="page-shell narrative-split"><div className="narrative-copy"><p className="eyebrow">El punto de partida</p><h2 id="problem-title">No faltan piezas. Falta conectarlas.</h2><p>Muchos pueblos ya tienen parte de lo que necesitan.</p><p>Una casa vacía. Un comercio sin relevo. Personas que necesitan cuidados. Un local municipal sin uso. Familias buscando otro lugar donde vivir. Un profesional que podría trabajar en varios municipios.</p><p>Por separado, ninguna de esas piezas resuelve demasiado. La oportunidad aparece cuando empiezan a encajar.</p><ul className="proposal-pieces">{proposalPieces.map((piece) => <li key={piece}>{piece}</li>)}<li className="proposal-pieces__result">Una oportunidad completa</li></ul></div><ConceptImage id="problema" caption="Escena conceptual: recursos y necesidades todavía dispersos." /></div></section>

    <section id="propuesta" className="narrative-section" aria-labelledby="proposal-title"><div className="page-shell narrative-split narrative-split--reverse"><ConceptImage id="propuesta" caption="Escena conceptual: un plan se construye con información y acuerdos locales." /><div className="narrative-copy"><p className="eyebrow">Un paso antes</p><h2 id="proposal-title">Antes de buscar personas, construyamos algo que pueda funcionar.</h2><p>Sinoikía trabaja un paso antes. No queremos publicar «se busca familia para vivir en este pueblo» y esperar que funcione.</p><p>Primero preguntamos: ¿De qué podría vivir? ¿Dónde podría vivir? ¿Hay demanda suficiente? ¿Qué servicios necesita? ¿Puede acceder a ellos aunque estén en otro pueblo? ¿Quién tiene que comprometerse? ¿Qué falta todavía?</p><p className="narrative-highlight">No buscamos llenar pueblos. Buscamos crear las condiciones para poder vivir en ellos.</p></div></div></section>

    <section className="narrative-section narrative-section--soft" aria-labelledby="discovery-title"><div className="page-shell narrative-split"><div className="narrative-copy"><p className="eyebrow">Descubrir posibilidades</p><h2 id="discovery-title">Y a veces la oportunidad todavía no existe.</h2><p>Un pueblo puede no tener suficiente demanda para mantener un servicio. Tres pueblos juntos, sí.</p><p>Un comercio puede no ser viable por sí solo. Combinado con reparto, otro servicio o varios municipios, quizá sí.</p><p>Una vivienda vacía puede no significar nada. Vinculada a una actividad, servicios accesibles y una persona adecuada, puede convertirse en parte de una solución.</p><p className="narrative-highlight">No solo reunimos oportunidades. Ayudamos a descubrirlas.</p></div><ConceptImage id="comercio" caption="Escena conceptual: varios pueblos colaboran para sostener una actividad." /></div></section>

    <section id="ejemplo" className="narrative-section example-section" aria-labelledby="example-title"><div className="page-shell"><div className="example-intro"><div><p className="eyebrow">Ejemplo conceptual</p><h2 id="example-title">Tres pueblos. Ninguno puede mantener una tienda.</h2><p>Hay demanda, pero está repartida. En lugar de asumir que el comercio es inviable, Sinoikía ayuda a explorar otra posibilidad: una pequeña tienda con reparto y puntos de recogida que dé servicio a los tres pueblos.</p></div><ConceptImage id="comercio" caption="Escena conceptual: el reparto conecta la actividad de varios pueblos." /></div><ExampleChecklist /><h3 className="example-status">El plan todavía no está listo.</h3><p className="example-outro">Sinoikía no oculta lo que falta para hacer viable una oportunidad. Lo convierte en el siguiente problema que hay que resolver.</p></div></section>

    <section id="como-funciona" className="narrative-section narrative-section--dark" aria-labelledby="process-title"><div className="page-shell"><p className="eyebrow">Cómo funciona</p><h2 id="process-title">De una necesidad a una oportunidad real.</h2><ol className="narrative-steps">{processSteps.map((step) => <li key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol></div></section>

    <section className="narrative-section territory-vision" aria-labelledby="territory-title"><div className="page-shell narrative-split"><div className="narrative-copy"><p className="eyebrow">Territorio compartido</p><h2 id="territory-title">La vida no entiende de términos municipales.</h2><p>El colegio puede estar a 8 minutos. El médico, a 12. El trabajo puede repartirse entre tres pueblos. Una furgoneta puede prestar servicio a cinco.</p><p>Sinoikía no pregunta si un pueblo tiene de todo. Pregunta si una persona puede acceder a todo lo que necesita. Por eso varios pueblos cercanos pueden funcionar como una misma comunidad.</p></div><ConceptImage id="territorio" caption="Escena conceptual: la vida cotidiana cruza límites municipales." /></div></section>

    <section className="narrative-section pathways-section" aria-labelledby="pathways-title"><div className="page-shell"><p className="eyebrow">Dos formas de empezar</p><h2 id="pathways-title">Una puerta para cada pregunta</h2><div className="pathways-grid"><article><ConceptImage id="personas" caption="Escena conceptual: conocer la vida cotidiana del lugar." /><div><p className="eyebrow">Personas</p><h3>Quiero vivir en un pueblo</h3><p>No empieces buscando una casa y resolviendo después el resto. Cuéntanos qué necesitas, qué sabes hacer y qué vida buscas. Sinoikía podrá mostrarte territorios donde esas piezas empiezan a encajar y qué cosas todavía no están resueltas.</p><Link className="button button--primary" to="/descubrir">Descubrir dónde encajo</Link></div></article><article><ConceptImage id="municipios" caption="Escena conceptual: una ruta compartida conecta pueblos cercanos." /><div><p className="eyebrow">Municipios</p><h3>Quiero activar mi pueblo</h3><p>No publiques necesidades aisladas. Reúne vivienda, actividad, servicios, recursos y necesidades. Sinoikía ayuda a explorar qué oportunidades podrían construirse y qué hace falta para convertirlas en realidad.</p><Link className="button button--ghost" to="/municipios">Activar mi municipio</Link></div></article></div></div></section>

    <section className="narrative-section narrative-section--soft" aria-labelledby="honesty-title"><div className="page-shell honesty-layout"><div className="narrative-copy"><p className="eyebrow">Honestidad</p><h2 id="honesty-title">Saber qué falta también importa.</h2><p>Vacía no significa disponible. Interesado no significa comprometido. Solicitado no significa concedido.</p><p>Sinoikía diferencia lo que sabemos, lo que estamos comprobando y lo que está realmente confirmado. Porque alguien que se plantea cambiar su vida necesita saber qué existe de verdad y qué todavía depende de algo o de alguien.</p></div><ul className="honesty-points"><li>Confirmado: existe y sus condiciones están comprobadas.</li><li>En comprobación: falta contrastar información.</li><li>Interés: hay una persona o entidad, pero no un compromiso.</li><li>Pendiente: una condición imprescindible sigue sin resolverse.</li></ul></div></section>

    <section className="closing-section" aria-labelledby="closing-title"><ConceptImage id="cierre" caption="Escena conceptual: una comunidad se reconoce en su vida cotidiana." /><div className="page-shell closing-section__copy"><p className="eyebrow">Habitar juntos</p><h2 id="closing-title">El futuro es rural.</h2><h3>Hagamos que también sea viable.</h3><p>Los pueblos no necesitan convertirse en pequeñas ciudades ni tener todos los servicios dentro de sus límites. Necesitan conectar mejor las viviendas, actividades, servicios, recursos y personas que ya existen, y descubrir qué sigue faltando.</p><p>Sinoikía quiere ayudar a convertir esas piezas dispersas en lugares donde quedarse tenga sentido.</p><div className="narrative-actions"><Link className="button button--light" to="/descubrir">Quiero descubrir dónde encajo</Link><Link className="button button--ghost button--ghost-light" to="/municipios">Quiero activar mi municipio</Link></div></div></section>
  </main>
}
